/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 12 17:56:51 GMT 2024
 */

package com.exemplo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.exemplo.Avaliacao;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Avaliacao_ESTest extends Avaliacao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(0.0, false, (-3212.901605927));
      assertEquals((-3212.901605927), avaliacao0.getFeedback(), 0.01);
      assertEquals(0.0, avaliacao0.getPontuacao(), 0.01);
      assertFalse(avaliacao0.isProjetoConcluido());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(1.0, false, 1.0);
      boolean boolean0 = avaliacao0.isProjetoConcluido();
      assertFalse(boolean0);
      assertEquals(1.0, avaliacao0.getFeedback(), 0.01);
      assertEquals(1.0, avaliacao0.getPontuacao(), 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(0.0, true, 0.0);
      double double0 = avaliacao0.getPontuacao();
      assertTrue(avaliacao0.isProjetoConcluido());
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, avaliacao0.getFeedback(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(1.0, false, 1.0);
      double double0 = avaliacao0.getPontuacao();
      assertEquals(1.0, double0, 0.01);
      assertEquals(1.0, avaliacao0.getFeedback(), 0.01);
      assertFalse(avaliacao0.isProjetoConcluido());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(1.0, false, 1.0);
      double double0 = avaliacao0.getFeedback();
      assertEquals(1.0, avaliacao0.getPontuacao(), 0.01);
      assertFalse(avaliacao0.isProjetoConcluido());
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao((-12.2083508), false, (-12.2083508));
      double double0 = avaliacao0.getFeedback();
      assertEquals((-12.2083508), avaliacao0.getPontuacao(), 0.01);
      assertFalse(avaliacao0.isProjetoConcluido());
      assertEquals((-12.2083508), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao((-12.2083508), false, (-12.2083508));
      double double0 = avaliacao0.getPontuacao();
      assertEquals((-12.2083508), avaliacao0.getFeedback(), 0.01);
      assertFalse(avaliacao0.isProjetoConcluido());
      assertEquals((-12.2083508), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao((-59.698), true, (-59.698));
      boolean boolean0 = avaliacao0.isProjetoConcluido();
      assertEquals((-59.698), avaliacao0.getPontuacao(), 0.01);
      assertTrue(boolean0);
      assertEquals((-59.698), avaliacao0.getFeedback(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Avaliacao avaliacao0 = new Avaliacao(0.0, true, 0.0);
      double double0 = avaliacao0.getFeedback();
      assertTrue(avaliacao0.isProjetoConcluido());
      assertEquals(0.0, avaliacao0.getPontuacao(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }
}
